
export const ADD_MOVIE_TO_WATCHLIST = "ADD_MOVIE_TO_WATCHLIST"; // Fixed name consistency
export const REMOVE_MOVIE_FROM_WATCHLIST = "REMOVE_MOVIE_FROM_WATCHLIST"; // Fixed incorrect declaration
export const ADD_MOVIE_TO_WATCHED = "ADD_MOVIE_TO_WATCHED";
export const REMOVE_MOVIE_FROM_WATCHED = "REMOVE_MOVIE_FROM_WATCHED";
export const MOVE_TO_WATCHLIST = "MOVE_TO_WATCHLIST";